package com.example.google_books.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF904A46)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDAD7)
val onPrimaryContainerLight = Color(0xFF733331)
val secondaryLight = Color(0xFF775654)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDAD7)
val onSecondaryContainerLight = Color(0xFF5D3F3D)
val tertiaryLight = Color(0xFF735B2E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDEA7)
val onTertiaryContainerLight = Color(0xFF594319)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F7)
val onBackgroundLight = Color(0xFF231919)
val surfaceLight = Color(0xFFFFF8F7)
val onSurfaceLight = Color(0xFF231919)
val surfaceVariantLight = Color(0xFFF5DDDB)
val onSurfaceVariantLight = Color(0xFF534342)
val outlineLight = Color(0xFF857371)
val outlineVariantLight = Color(0xFFD8C2C0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382E2D)
val inverseOnSurfaceLight = Color(0xFFFFEDEB)
val inversePrimaryLight = Color(0xFFFFB3AE)
val surfaceDimLight = Color(0xFFE8D6D4)
val surfaceBrightLight = Color(0xFFFFF8F7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0EF)
val surfaceContainerLight = Color(0xFFFCEAE8)
val surfaceContainerHighLight = Color(0xFFF6E4E2)
val surfaceContainerHighestLight = Color(0xFFF1DEDD)

val primaryDark = Color(0xFFFFB3AE)
val onPrimaryDark = Color(0xFF571D1C)
val primaryContainerDark = Color(0xFF733331)
val onPrimaryContainerDark = Color(0xFFFFDAD7)
val secondaryDark = Color(0xFFE7BDB9)
val onSecondaryDark = Color(0xFF442928)
val secondaryContainerDark = Color(0xFF5D3F3D)
val onSecondaryContainerDark = Color(0xFFFFDAD7)
val tertiaryDark = Color(0xFFE2C28C)
val onTertiaryDark = Color(0xFF402D04)
val tertiaryContainerDark = Color(0xFF594319)
val onTertiaryContainerDark = Color(0xFFFFDEA7)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1A1111)
val onBackgroundDark = Color(0xFFF1DEDD)
val surfaceDark = Color(0xFF1A1111)
val onSurfaceDark = Color(0xFFF1DEDD)
val surfaceVariantDark = Color(0xFF534342)
val onSurfaceVariantDark = Color(0xFFD8C2C0)
val outlineDark = Color(0xFFA08C8B)
val outlineVariantDark = Color(0xFF534342)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF1DEDD)
val inverseOnSurfaceDark = Color(0xFF382E2D)
val inversePrimaryDark = Color(0xFF904A46)
val surfaceDimDark = Color(0xFF1A1111)
val surfaceBrightDark = Color(0xFF423736)
val surfaceContainerLowestDark = Color(0xFF140C0C)
val surfaceContainerLowDark = Color(0xFF231919)
val surfaceContainerDark = Color(0xFF271D1D)
val surfaceContainerHighDark = Color(0xFF322827)
val surfaceContainerHighestDark = Color(0xFF3D3231)






